# Base configs
baseurl: "https://Luxvca.github.io/LuxMedia"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Luca Martinez"
subtitle: "See the world through my eyes!"
author: "Ram Patra"
header:
 title: "Photography"
 subtitle: "by Luca Martinez"
footer:
 name: "Hey there, my name is Luca"
 bio: "I am a photographer and a tech aficionado from Los Angeles. Love solving the teeny tiny problems in life and now learning photography."
 github: "Want to work? Just email: <a href=\"mail.lucamartinez@gmail.com">"
web_design: "Lux"
social_urls:
  instagram: "https://www.instagram.com/luxvca/"
  linkedin: "https://www.linkedin.com/in/luca-martinez-a93565202/"
